print('\n'*3)
print('---------------------')
print('first python program')
print('---------------------')
print('\n')
name=input('what is your name?:')
print('\n'*3)
print('hello',name)
print('\n')
print('welcome to python programming')
print('\n'*2)
