fname = input('Enter First Name')
lastn = input('Enter Last Name')
address = input('Enter Address')
city = input('Enter City')
scode = input('Enter state')
pcode=input('Enter Postel Code')
fulln = fname + " " +lastn
print(fulln)
print(address)
print(city,scode,pcode)
