from turtle import * 
import time
def main():
    print('\n'*40)
    speed(4)

    shape('square')
    pencolor('black')
    fillcolor('blue')
    penup()
    goto(-5,-100)
    pendown()
    begin_fill()
    forward(250)
    right(150)
    forward(150)
    right(60)
    forward(150)
    end_fill()
    penup()
    home()
    pencolor('green')
    penup()
    goto(0,0)
    pensize(20)
    pendown()
    forward(200)
    penup()
    pencolor('red')
    pensize(5)
    setposition(100,-200)
    pendown()
    circle(200)
    penup()
    pencolor('yellow')
    pensize(5)
    setposition(-2,50)
    pendown()
    fillcolor('yellow')
    begin_fill()
    circle(50)
    end_fill()
    penup()
    pencolor('black')
    pensize(5)
    setposition(200,50)
    pendown()
    fillcolor('black')
    begin_fill()
    circle(50)
    end_fill()
    penup()
    home()
    print(' ---done--- ')
main()
